app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::group(['middleware' => ['auth']], function () {
	Route::resource('address','AddressController');
});

Route::group(array('prefix' => 'api'), function() {
    Route::resource('address','AddressApiController');
});

app/Http/Controllers/AddressController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Address;
use Illuminate\Http\Request;
use Session;

class AddressController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('address.view');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('address.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $req)
	{

			$address = new Address();

    	$res = $address->validateAddress($req->all());

    	if ($res->fails()) {
            return redirect('address/create')
                        ->withErrors($res)
                        ->withInput();
        }
        else{

        	$saveYN = $address->saveAddress($req->all());
        	if($saveYN){
        		Session::flash('message','Record Saved Successfully');
        		return redirect('address/create');
        	}
        	else{
        		Session::flash('error','Record not Saved Successfully');
        		return redirect('address/create');
        	}

        }
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$recId = Address::findOrFail($id);
    	//dd($recId);
    return view('address.edit',compact('recId'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Request $req, $id)
	{
			$address = new Address();
    	$res = $address->validateAddress($req->all());

    	if ($res->fails()) {
        return redirect()->route('address.edit',$id)
                      ->withErrors($res)
                      ->withInput();
      }
      else {
      	$saveYN = $address->updateAddress($req->all(), $id);
      	if($saveYN){
      		Session::flash('message','Record Update Successfully');
      		return redirect()->route('address.edit',$id);
      	}
      	else{
      		Session::flash('error','Record not Updated Successfully');
      		return redirect()->route('address.edit',$id);
      	}
      }
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$recId = Address::findOrFail($id);
    $recId->delete();
    	if($recId){
      	Session::flash('message','Record deleted Successfully');
        return redirect()->route('address.index');
    	}
    	else{
    		Session::flash('error','Record not deletd Successfully');
    		return redirect()->route('address.index');
    	}
	}

}

resources/views/address/create.blade.php
@extends('app')

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading">Address</div>
				<div class="panel-body">
					@if(session()->has('message'))
            <div class="alert alert-success" role="alert">
                {{session()->get('message')}}
            </div>
          @endif
					@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Whoops!</strong> There were some problems with your input.<br><br>
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif

					<form class="form-horizontal" role="form" method="POST" action="{{route('address.store')}}">
						<input type="hidden" name="_token" value="{{ csrf_token() }}">

						<div class="form-group">
							<label class="col-md-4 control-label">Title</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="title" value="{{ old('title') }}">
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label">Number</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="number" value="{{ old('number') }}">
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label">Address Line1</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="addressline1" value="{{ old('addressline1') }}">
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label">Address Line2</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="addressline2" value="{{ old('addressline2') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="addressline3" class="col-md-4 control-label">Address Line3</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="addressline3" value="{{ old('addressline3') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="pincode" class="col-md-4 control-label">Pin Code</label>
							<div class="col-md-6">
								<input type="number" class="form-control" name="pincode" value="{{ old('pincode') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="city" class="col-md-4 control-label">City</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="city" value="{{ old('city') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="state" class="col-md-4 control-label">State</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="state" value="{{ old('state') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="country" class="col-md-4 control-label">Country</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="country" value="{{ old('country') }}">
							</div>
						</div>

						<div class="form-group {{ $errors->has('address_cat') ? ' has-error' : '' }}">
              <label for="address_cat" class="col-md-4 control-label">Address Category</label>
               <div class="input-group col-md-8">
                  <input type="radio" name="address_cat" value="f"/> Default From&nbsp;&nbsp;
									 <input type="radio" name="address_cat" value="t"/> Default To
                  @if ($errors->has('countryId'))
                      <span class="help-block">
                          <strong>{{ $errors->first('country') }}</strong>
                      </span>
                  @endif
              </div>

          	</div>


						<div class="form-group">
							<div class="col-md-offset-1 col-md-6 ">
								<button type="submit" class="btn btn-primary">
									Save
								</button>
							</div>
							<div class="col-md-2 col-md-offset-2">
								<a href="{{route('address.index')}}" class="btn btn-primary">
									View
								</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/address/edit.blade.php
@extends('app')

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
				<div class="panel-heading">Address</div>
				<div class="panel-body">
					@if(session()->has('message'))
            <div class="alert alert-success" role="alert">
                {{session()->get('message')}}
            </div>
          @endif
					@if (count($errors) > 0)
						<div class="alert alert-danger">
							<strong>Whoops!</strong> There were some problems with your input.<br><br>
							<ul>
								@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
								@endforeach
							</ul>
						</div>
					@endif

					<form class="form-horizontal" role="form" method="POST" action="{{route('address.update',$recId->id)}}">
						<input type="hidden" name="_method" value="PUT">
	 				  <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">

						<div class="form-group">
							<label class="col-md-4 control-label">Title</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="title" value="{{ $recId->title or old('title') }}">
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label">Number</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="number" value="{{ $recId->number or old('number') }}">
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label">Address Line1</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="addressline1" value="{{ $recId->addressline1 or old('addressline1') }}">
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-4 control-label">Address Line2</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="addressline2" value="{{ $recId->addressline2 or old('addressline2') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="addressline3" class="col-md-4 control-label">Address Line3</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="addressline3" value="{{ $recId->addressline3 or  old('addressline3') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="pincode" class="col-md-4 control-label">Pin Code</label>
							<div class="col-md-6">
								<input type="number" class="form-control" name="pincode" value="{{ $recId->pincode or old('pincode') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="city" class="col-md-4 control-label">City</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="city" value="{{ $recId->city or old('city') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="state" class="col-md-4 control-label">State</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="state" value="{{ $recId->state or old('state') }}">
							</div>
						</div>

						<div class="form-group">
							<label for="country" class="col-md-4 control-label">Country</label>
							<div class="col-md-6">
								<input type="text" class="form-control" name="country" value="{{ $recId->country or old('country') }}">
							</div>
						</div>

						<div class="form-group {{ $errors->has('address_cat') ? ' has-error' : '' }}">
              <label for="address_cat" class="col-md-4 control-label">Address Category</label>
               <div class="input-group col-md-8">
                  <input type="checkbox" name="address_cat" value="f" @if($recId->address_cat === 'f') checked @endif/> Default From&nbsp;&nbsp;
									<input type="checkbox" name="address_cat" value="t" @if($recId->address_cat === 't') checked @endif/> Default To
                  @if ($errors->has('countryId'))
                      <span class="help-block">
                          <strong>{{ $errors->first('country') }}</strong>
                      </span>
                  @endif
              </div>

          	</div>


						<div class="form-group">
							<div class="col-md-offset-1 col-md-6 ">
								<button type="submit" class="btn btn-primary">
									Save
								</button>
							</div>
							<div class="col-md-2 col-md-offset-2">
								<a href="{{route('address.index')}}" class="btn btn-primary">
									View
								</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/address/view.blade.php
@extends('app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-offset-1 col-md-10 col-md-offset-1">
            <div class="panel panel-default">

                <div class="panel-heading">
                        All Address
                        <a href="{{ route('address.create') }}" class="btn btn-primary pull-right">Create</a>

                     <div class="clearfix"></div>
                </div>
                <div class="panel-body">
                    @if(session()->has('message'))
                    <div class="alert alert-success" role="alert">
                        {{session()->get('message')}}
                    </div>
                    @endif
                    @if(session()->has('error'))
                    <div class="alert alert-danger" role="alert">
                        {{session()->get('error')}}
                    </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-responsive table-striped table-bordered table-hover no-margin">
                          <thead>
                            <tr>
                             <th>Serial No.</th>
                             <th>Title</th>
                             <th>Number</th>
                             <th>Address Line1</th>
                             <th>Address Line2</th>
                             <th>Address Line3</th>
                             <th>country</th>
                             <th>City</th>
                             <th>Pin code</th>
                             <th>Address Category</th>
                             <th colspan="2" style="width:10%; text-align: center">Action</th>
                           </tr>
                         </thead>
                         <tbody>
                         <?php $i=1; ?>
                         @foreach(\App\Address::paginate(10) as $address)
                           <tr>
                             <td>{{$i++}}</td>
                             <td>{{$address->title}}</td>
                             <td>{{$address->number}}</td>
                             <td>{{$address->addressline1}}</td>
                             <td>{{$address->addressline2}}</td>
                             <td>{{$address->addressline3}}</td>
                             <td>{{$address->country}}</td>
                             <td>{{$address->city}}</td>
                             <td>{{$address->pincode}}</td>
                             <td>
                               @if($address->address_cat === 'f')
                                Default From
                               @elseif($address->address_cat === 't')
                                Default To
                               @endif
                             </td>
                             <td><a href="{{route('address.edit',$address->id)}}" class="btn btn-xs btn-danger">Edit</a></td>
                             <td>
                              <form action="{{route('address.destroy',$address->id)}}" method="post" id="confirm">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
                                <input type="submit" value="Del" class="btn btn-xs btn-danger" type="button">
                              </form>
                             </td>
                           </tr>
                         @endforeach
                         </tbody>
                      </table>
                   </div>
                    {!! \App\Address::paginate(10)->render() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection